#!/bin/bash

_RED="\e[1;31m"
_GREEN="\e[1;32m"
_YELLOW="\e[1;33m"
_RESET="\e[1;0m"
INSTALL_USER=`getent passwd ${USER} | cut -d: -f3`
INSTALL_GROUP=`getent passwd ${USER} | cut -d: -f4`
INSTALL_DIR=`getent passwd ${USER} | cut -d: -f6`

install_config() {
	install -m 0644 -o ${INSTALL_USER} -g ${INSTALL_GROUP} vimrc ${INSTALL_DIR}/.vimrc
  
  for file in `find bundle -type f -print`; do
    set -x
    install -Dm 0644 $file ${INSTALL_DIR}/.vim/${file}
    { set +x; } 2>/dev/null
  done 

  echo -e $_YELLOW"Install vim plugins. This can take a few minutes..."$_RESET
  yes | vim +PluginInstall +qall > /dev/null 2>&1

	[[ $? == 0 ]] && echo -e $_GREEN"Install complete"$_RESET || echo -e $_RED"Install failed"$_RESET
}

preinstall() {
  echo -e $_YELLOW"Fetch Vundle.vim module"$_RESET
  git submodule update --init --recursive --force
}

[[ ! -z $1 ]] && {
	getent passwd $1 &> /dev/null
	if [[ $? == 0 ]]
	then
		INSTALL_USER=`getent passwd $1 | cut -d: -f3`
		INSTALL_DIR=`getent passwd $1 | cut -d: -f6`
		INSTALL_GROUP=`getent passwd $1 | cut -d: -f4`

		exit 0
	else
		 echo -e $_RED"User $1 doesn't exist"$_RESET && exit -1
	fi
} 

echo -e $_YELLOW"Begin installation of vim configuration files and plugins"$_RESET

preinstall
install_config

exit 0
